// Code generated by hero.
// source: C:\Users\David Yap\Desktop\go\src\app\template\userlist.html
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func UserList(name string, buffer *bytes.Buffer) {
	buffer.WriteString(`<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <style>
            body{
                background: linear-gradient(ltr, blue, yellow);
                color: red;
            }
        </style>
    </head>

    <body>
        `)
	buffer.WriteString(`
    <img src="https://picsum.photos/id/237/200/300" alt="Dog Picture">
    <ul>
        <li>Your name : `)
	hero.EscapeHTML(name, buffer)
	buffer.WriteString(`</li>
    </ul>
`)
	buffer.WriteString(`
    </body>
</html>`)

}
